const assert=require('node:assert/strict'),path=require('node:path');
const p=require(require.resolve('puppeteer',{paths:[path.resolve(__dirname,'../../../..')]}));
(async()=>{const browser=await p.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});
try{const page=await browser.newPage(),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
await page.setViewport({width:1600,height:1000});await page.goto('http://127.0.0.1:8931/atlas/');
assert.equal(await page.title(),'메이커스랩 · 워커 관제');await page.waitForSelector('body[data-ready="true"]');
assert.equal(await page.$eval('#total',e=>e.textContent),'200');
await page.screenshot({path:path.resolve(__dirname,'../.artifacts/atlas-overview.png')});
await page.type('#search','W-001');await page.waitForSelector('[data-result="W-001"]');await page.click('[data-result="W-001"]');
await page.waitForFunction(()=>document.querySelector('#detail').textContent.includes('W-001'));
await new Promise(r=>setTimeout(r,800));await page.screenshot({path:path.resolve(__dirname,'../.artifacts/atlas-worker.png')});
await page.click('#follow-project');assert((await page.$eval('#detail',e=>e.textContent)).includes('수집 안정화'));
await page.screenshot({path:path.resolve(__dirname,'../.artifacts/atlas-project.png')});
await page.click('#home');await page.select('#status','blocked');assert.equal(await page.$eval('#matches',e=>e.textContent),'10');
await page.click('[data-result]');await page.click('#logs');assert((await page.$eval('#log-content',e=>e.textContent)).includes('demo-'));
await page.click('#home');const before=await page.evaluate(()=>atlasDiagnostics().zoom);await page.mouse.move(900,450);await page.mouse.wheel({deltaY:-550});await new Promise(r=>setTimeout(r,400));assert((await page.evaluate(()=>atlasDiagnostics().zoom))>before);
const targetBefore=await page.evaluate(()=>atlasDiagnostics().target);await page.mouse.move(850,500);await page.mouse.down();await page.mouse.move(1000,600,{steps:8});await page.mouse.up();await new Promise(r=>setTimeout(r,300));assert.notDeepEqual(await page.evaluate(()=>atlasDiagnostics().target),targetBefore);
await page.click('#home');await new Promise(r=>setTimeout(r,350));const pt=await page.evaluate(()=>{const p=atlasDiagnostics().points.find(p=>p.id==='W-065'),r=document.querySelector('#scene').getBoundingClientRect();return {x:p.x+r.left,y:p.y+r.top};});await page.mouse.click(pt.x,pt.y);assert((await page.$eval('#detail',e=>e.textContent)).includes('W-065'));
await page.click('#home');await page.type('#search','not-a-worker');assert.equal(await page.$eval('#matches',e=>e.textContent),'0');
// Selection scope must not silently replace search scope after closing details.
await page.click('#home');await page.click('[data-result="W-001"]');await page.click('#logs');await page.click('[data-result="W-002"]');assert(await page.$eval('#log-pane',e=>e.hidden),'stale logs must close on worker change');
await page.click('#follow-project');await page.click('#close-detail');
const restored=await page.evaluate(()=>atlasDiagnostics().activeCount);assert.equal(restored,200,'closing project restores original filter');
await page.click('#home');await new Promise(r=>setTimeout(r,350));const origin=await page.evaluate(()=>{const p=atlasDiagnostics().points.find(p=>p.id==='W-065'),r=document.querySelector('#scene').getBoundingClientRect();return{x:p.x+r.left,y:p.y+r.top};});
await page.mouse.move(origin.x,origin.y);await page.mouse.down();await page.mouse.move(origin.x+45,origin.y,{steps:5});await page.mouse.move(origin.x,origin.y,{steps:5});await page.mouse.up();assert(await page.$eval('#detail',e=>e.hidden),'round-trip drag must not select');
await page.click('#home');const orbitBefore=await page.evaluate(()=>atlasDiagnostics().points[64]);await page.click('#orbit');await page.mouse.move(900,450);await page.mouse.down();await page.mouse.move(1080,500,{steps:10});await page.mouse.up();await new Promise(r=>setTimeout(r,300));assert.notDeepEqual(await page.evaluate(()=>atlasDiagnostics().points[64]),orbitBefore,'orbit changes projected location');await page.click('#orbit');
await page.click('#home');await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.reload();await page.waitForSelector('body[data-ready="true"]');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert(await page.evaluate(()=>atlasDiagnostics().points.every(p=>p.visible)),'mobile whole view includes every worker');
const cdp=await page.createCDPSession(),touch=(type,points)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});
const touchZoom=await page.evaluate(()=>atlasDiagnostics().zoom);await touch('touchStart',[{x:145,y:280,id:1},{x:245,y:380,id:2}]);await touch('touchMove',[{x:100,y:240,id:1},{x:290,y:420,id:2}]);await touch('touchEnd',[]);await new Promise(r=>setTimeout(r,300));assert((await page.evaluate(()=>atlasDiagnostics().zoom))>touchZoom,'touch pinch zoom');assert(await page.$eval('#detail',e=>e.hidden),'pinch must not select');
await page.click('#open-search');await page.type('#search','W-200');await page.click('[data-result="W-200"]');assert((await page.$eval('#detail',e=>e.textContent)).includes('W-200'));await new Promise(r=>setTimeout(r,450));await page.screenshot({path:path.resolve(__dirname,'../.artifacts/atlas-mobile.png')});
assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);console.log('PASS: 200 seats, search, project, blocked, logs, zoom, pan, ray selection, empty, mobile, no writes, no page errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
