const assert=require('node:assert/strict'),path=require('node:path');
const p=require(require.resolve('puppeteer',{paths:[path.resolve(__dirname,'../../../..')]}));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await p.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});try{
 const page=await b.newPage(),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});await page.setViewport({width:1600,height:1000});await page.goto('http://127.0.0.1:8931/studio/');assert.equal(await page.title(),'메이커스랩 · 워커 스튜디오');await page.waitForSelector('body[data-ready=true]');await pause(1500);
 assert.equal(await page.$$eval('[data-worker]',es=>es.length),8);assert.equal(await page.$eval('#count',e=>e.textContent),'8');await page.screenshot({path:path.resolve(__dirname,'../.artifacts/studio-day.png')});
 await page.click('[data-worker="W-001"]');await pause(1200);assert((await page.$eval('#detail',e=>e.textContent)).includes('W-001'));await page.screenshot({path:path.resolve(__dirname,'../.artifacts/studio-worker.png')});
 await page.click('[data-worker="W-020"]');await pause(1000);assert((await page.$eval('#detail',e=>e.textContent)).includes('막힘'));
 await page.click('#home');await pause(1000);await page.click('#night');await pause(1000);assert.equal(await page.$eval('#night',e=>e.getAttribute('aria-pressed')),'true');await page.screenshot({path:path.resolve(__dirname,'../.artifacts/studio-night.png')});
 await page.click('#motion');assert.equal(await page.$eval('#motion',e=>e.getAttribute('aria-pressed')),'false');
 await page.click('#night');await page.click('#home');await pause(800);const before=await page.evaluate(()=>studioDiagnostics().camera);await page.mouse.move(900,450);await page.mouse.down();await page.mouse.move(1040,480,{steps:10});await page.mouse.up();await pause(350);assert.notDeepEqual(await page.evaluate(()=>studioDiagnostics().camera),before);
 await page.click('#home');await pause(900);const pt=await page.evaluate(()=>studioDiagnostics().points.find(p=>p.id==='W-003'));await page.mouse.click(pt.x,pt.y);await pause(800);assert((await page.$eval('#detail',e=>e.textContent)).includes('W-003'));
 await page.click('[data-worker="W-001"]');await page.click('#zoom-in');await pause(70);const zoomed=await page.evaluate(()=>studioDiagnostics().camera);await pause(900);const settled=await page.evaluate(()=>studioDiagnostics().camera);assert(Math.hypot(...settled.map((v,i)=>v-zoomed[i]))<.001,'zoom cancels camera transition');
 await page.setViewport({width:900,height:600});await page.click('[data-worker="W-020"]');await pause(900);assert(await page.evaluate(()=>document.querySelector('#detail').getBoundingClientRect().bottom<=document.querySelector('footer').getBoundingClientRect().top),'short viewport detail stays above roster');
 await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.reload();await page.waitForSelector('body[data-ready=true]');await pause(600);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.click('[data-worker="W-015"]');await pause(900);await page.screenshot({path:path.resolve(__dirname,'../.artifacts/studio-mobile.png')});assert((await page.$eval('#detail',e=>e.textContent)).includes('대기'));assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);console.log('PASS studio: 8 workers, selection, blocked/waiting, home, day/night, motion toggle, orbit, raycast, mobile, no writes/errors');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
