const assert=require('node:assert/strict'),path=require('node:path');
const p=require(require.resolve('puppeteer',{paths:[path.resolve(__dirname,'../../../..')]}));
const pause=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const b=await p.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--enable-unsafe-swiftshader']});try{
 const page=await b.newPage(),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.method()!=='GET')writes.push(r.url());});
 await page.setViewport({width:1600,height:1000});await page.goto('http://127.0.0.1:8931/universe/');assert.equal(await page.title(),'메이커스랩 · 유니버스');await page.waitForSelector('body[data-ready=true]');await pause(1100);
 const diag=()=>page.evaluate(()=>universeDiagnostics());assert.equal((await diag()).view,'outside');await page.screenshot({path:path.resolve(__dirname,'../.artifacts/universe-outside.png')});
 const buildingPoint=(await diag()).buildings?.find(b=>b.id==='shortem');assert(buildingPoint,'building projection available');await page.mouse.click(buildingPoint.x,buildingPoint.y);await pause(900);assert.equal((await diag()).view,'entrance');await page.click('#enter');await pause(1400);assert.equal((await diag()).view,'inside');assert.equal((await diag()).workers.length,16);assert.equal(new Set((await diag()).workers.map(w=>w.id)).size,16);await page.screenshot({path:path.resolve(__dirname,'../.artifacts/universe-inside.png')});
 await page.click('[data-room="plan"]');await pause(1000);await page.click('[data-worker="W-001"]');await pause(1000);assert((await page.$eval('#detail',e=>e.textContent)).includes('팀장'));await page.screenshot({path:path.resolve(__dirname,'../.artifacts/universe-leader.png')});
 await page.click('[data-room="dev"]');await pause(1000);assert.equal((await diag()).room,'dev');const workerPoint=(await diag()).workers.find(w=>w.id==='W-034');await page.mouse.click(workerPoint.x,workerPoint.y);await pause(900);assert.equal((await diag()).selected,'W-034');await page.click('[data-room="qa"]');await pause(1000);assert.equal((await diag()).room,'qa');
 await page.click('#overview');await pause(1000);const crossPoint=(await diag()).workers.find(w=>w.id==='W-034');await page.mouse.click(crossPoint.x,crossPoint.y);await pause(900);assert.equal((await diag()).room,'dev');assert.equal(await page.$$eval('[data-worker]',es=>es.length),4,'worker selection synchronizes room roster');
 await page.click('#night');assert.equal((await diag()).night,true);await page.click('#overview');await pause(1000);await page.screenshot({path:path.resolve(__dirname,'../.artifacts/universe-night.png')});
 const before=(await diag()).camera;await page.mouse.move(900,650);await page.mouse.down();await page.mouse.move(1050,650,{steps:8});await page.mouse.up();await pause(500);assert.notDeepEqual((await diag()).camera,before,'orbit changes camera');assert.equal((await diag()).selected,null,'drag does not select');
 await page.click('#outside');await pause(900);assert.equal((await diag()).view,'outside');assert.equal((await diag()).selected,null);
 await page.setViewport({width:390,height:844,isMobile:true,hasTouch:true});await page.reload();await page.waitForSelector('body[data-ready=true]');await page.click('[data-building="shortem"]');await page.click('#enter');await pause(1000);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.resolve(__dirname,'../.artifacts/universe-mobile.png')});assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);console.log('PASS universe entry, 3 rooms, 16 unique workers, leader, return, night, mobile, no writes/errors');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
