import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildACampus} from './campus-a-art.js';
const $=s=>document.querySelector(s),canvas=$('#scene'),scene=new T.Scene();scene.background=new T.Color('#c5d2d4');scene.fog=new T.Fog('#c5d2d4',210,410);
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;
const camera=new T.PerspectiveCamera(44,1,.3,700),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=12;controls.maxDistance=340;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.48;
const pmrem=new T.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment,.04).texture;scene.environmentIntensity=.36;environment.dispose();pmrem.dispose();
const hemi=new T.HemisphereLight('#dce9f0','#647853',1.35);scene.add(hemi);const sun=new T.DirectionalLight('#ffe6bb',3.1);sun.position.set(-70,110,35);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-115,right:115,top:115,bottom:-115,near:1,far:280});sun.shadow.normalBias=.06;sun.shadow.bias=-.00008;scene.add(sun);
const ground=new T.Mesh(new T.PlaneGeometry(1200,1200),new T.MeshStandardMaterial({color:'#7b8d6b',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-1.02;ground.receiveShadow=true;scene.add(ground);
const campus=buildACampus(scene);let night=false,transition=null,current='front';
const views={front:{position:[0,70,126],target:[0,2,-8]},left:{position:[-130,65,80],target:[0,2,-8]},rear:{position:[25,75,-145],target:[0,2,-8]},hq:{position:[22,25,4],target:[0,8,-34]},shortem:{position:[-57,20,35],target:[-36,5,-4]}};
function view(id,immediate=false){current=id;const v=views[id],pos=new T.Vector3(...v.position),target=new T.Vector3(...v.target);if(innerWidth<700)pos.sub(target).multiplyScalar(1.6).add(target);if(immediate||matchMedia('(prefers-reduced-motion: reduce)').matches){camera.position.copy(pos);controls.target.copy(target);controls.update();transition=null;}else transition={at:performance.now(),from:camera.position.clone(),to:pos,start:controls.target.clone(),end:target};document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)));}
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas.parentElement);resize();
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
function freeView(){transition=null;current='free';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'));}
controls.addEventListener('start',freeView);
for(const [id,f]of [['in',.82],['out',1.22]])$('#'+id).onclick=()=>{freeView();const d=camera.position.clone().sub(controls.target);d.setLength(T.MathUtils.clamp(d.length()*f,12,340));camera.position.copy(controls.target).add(d);};
$('#night').onclick=()=>{night=!night;$('#night').setAttribute('aria-pressed',String(night));$('#night').textContent=night?'주간':'야간';scene.background.set(night?'#101e36':'#c5d2d4');scene.fog.color.copy(scene.background);ground.material.color.set(night?'#223844':'#7b8d6b');hemi.intensity=night?.35:1.35;sun.intensity=night?.22:3.1;sun.color.set(night?'#92b4f0':'#ffe6bb');scene.environmentIntensity=night?.16:.36;campus.setNight(night);};
$('#compare').onclick=()=>{const open=$('#reference').hidden;$('#reference').hidden=!open;$('#compare').setAttribute('aria-pressed',String(open));};$('#close-reference').onclick=()=>{$('#reference').hidden=true;$('#compare').setAttribute('aria-pressed','false');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#reference').hidden=true;$('#compare').setAttribute('aria-pressed','false');view('front');}});
const labelPoints=[{id:'hq-label',point:new T.Vector3(0,20,-34)},{id:'shortem-label',point:new T.Vector3(-36,14,-4)},{id:'stock-label',point:new T.Vector3(36,14,-4)}];
view('front',true);renderer.setAnimationLoop(time=>{if(transition){const t=Math.min(1,(time-transition.at)/1000),k=1-(1-t)**3;camera.position.lerpVectors(transition.from,transition.to,k);controls.target.lerpVectors(transition.start,transition.end,k);if(t===1)transition=null;}controls.update();renderer.render(scene,camera);const r=canvas.getBoundingClientRect();for(const l of labelPoints){const p=l.point.clone().project(camera),el=$('#'+l.id);el.hidden=camera.position.distanceTo(controls.target)<90||Math.abs(p.x)>.95||Math.abs(p.y)>.9||p.z>1;el.style.left=(p.x+1)*r.width/2+'px';el.style.top=(1-p.y)*r.height/2+'px';}});
window.campusDiagnostics=()=>({view:current,night,camera:camera.position.toArray(),buildings:campus.buildingCount,trees:campus.treeCount,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles});document.body.dataset.ready='true';
