import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildStudio,studioWorkers} from './studio-art.js';
import {counts,statusNames} from './atlas-data.js';
const $=s=>document.querySelector(s),canvas=$('#scene');
const scene=new T.Scene();scene.background=new T.Color('#ece9df');
const renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
const camera=new T.PerspectiveCamera(35,1,.1,150),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=55;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.47;controls.mouseButtons.LEFT=T.MOUSE.ROTATE;controls.mouseButtons.RIGHT=T.MOUSE.PAN;
const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;scene.environmentIntensity=.38;room.dispose();pmrem.dispose();
const hemisphere=new T.HemisphereLight('#fffaf0','#718c93',.9);scene.add(hemisphere);
const sun=new T.DirectionalLight('#fff0d5',2.4);sun.position.set(-13,22,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-17,right:17,top:15,bottom:-15,near:1,far:65});sun.shadow.normalBias=.025;sun.shadow.bias=-.00015;sun.shadow.radius=3;scene.add(sun);
const fill=new T.DirectionalLight('#dceef4',.7);fill.position.set(10,10,-2);scene.add(fill);
const floor=new T.Mesh(new T.PlaneGeometry(160,160),new T.MeshStandardMaterial({color:'#e5e4da',roughness:.95}));floor.rotation.x=-Math.PI/2;floor.position.y=-.5;floor.receiveShadow=true;scene.add(floor);
const lamps=[];for(const x of [-6.6,2.2])for(const z of [-2.8,3]){const l=new T.PointLight('#ffdaaa',0,8,2);l.position.set(x-1,2.8,z);scene.add(l);lamps.push(l);}
const studio=buildStudio(scene);let selected=null,transition=null,night=false,motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;$('#motion').setAttribute('aria-pressed',String(motion));
const rect=()=>canvas.getBoundingClientRect();function resize(){const r=rect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas.parentElement);resize();
function move(position,target,immediate=false){if(immediate||matchMedia('(prefers-reduced-motion: reduce)').matches){camera.position.copy(position);controls.target.copy(target);controls.update();transition=null;return;}transition={at:performance.now(),from:camera.position.clone(),to:position,start:controls.target.clone(),end:target};}
function home(immediate=false){selected=null;studio.workers.forEach(w=>w.ring.visible=false);$('#detail').hidden=true;$('#view-title').textContent='기획·리서치 스튜디오';document.querySelectorAll('[data-worker]').forEach(e=>e.setAttribute('aria-pressed','false'));move(new T.Vector3(innerWidth<700?25:16,innerWidth<700?32:19,innerWidth<700?42:23),new T.Vector3(0,.5,-.3),immediate);}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function select(id){const w=studio.workers.find(w=>w.data.id===id);if(!w)return;selected=w;studio.workers.forEach(v=>v.ring.visible=v===w);document.querySelectorAll('[data-worker]').forEach(e=>e.setAttribute('aria-pressed',String(e.dataset.worker===id)));$('#view-title').textContent=`${id} / ${w.data.task}`;
 const target=w.point.clone();target.y=innerWidth<700?.6:1.1;move(target.clone().add(new T.Vector3(3.1,2.5,4.5)),target);
 const d=$('#detail');d.replaceChildren();d.hidden=false;const top=el('div',undefined,'detail-heading');top.append(el('span','WORKER DETAIL / 예시','eyebrow'));const close=el('button','×');close.id='close-detail';close.setAttribute('aria-label','워커 상세 닫기');close.onclick=()=>home();top.append(close);d.append(top,el('h2',id),el('strong',w.data.task),el('span',statusNames[w.data.status],`state ${w.data.status}`),el('p',w.data.reason));
 const dl=el('dl');for(const [k,v] of [['역할',w.data.role],['보고',w.data.reportTo],['소속','기획·리서치'],['실행','실제 시스템 미연결']])dl.append(el('dt',k),el('dd',v));d.append(dl,el('small','화면·자료·동작은 디자인 검토용 예시입니다.'));}
const total=counts(studioWorkers);$('#count').textContent=total.total;$('#summary').textContent=`실행 ${total.running} · 대기 ${total.waiting} · 막힘 ${total.blocked}`;
studio.workers.forEach((w,i)=>{const b=el('button',undefined,'worker-chip');b.dataset.worker=w.data.id;b.setAttribute('aria-pressed','false');b.style.setProperty('--accent',w.accent);const avatar=el('span',undefined,'avatar');avatar.append(el('i'),el('i'));const t=el('span',undefined,'chip-text');t.append(el('b',w.data.id),el('small',w.data.task));b.append(avatar,t,el('span',statusNames[w.data.status],`state ${w.data.status}`));b.onclick=()=>select(w.data.id);$('#workers').append(b);});
const labels=studio.workers.map(w=>{const e=el('div',undefined,'seat-label');e.append(el('strong',w.data.id),el('span',w.data.task));e.style.setProperty('--accent',w.accent);$('#labels').append(e);return e;});
$('#night').onclick=()=>{night=!night;document.body.classList.toggle('night',night);$('#night').setAttribute('aria-pressed',String(night));$('#night').textContent=night?'☀ 주간으로':'☾ 야간으로';scene.background.set(night?'#202d3d':'#ece9df');hemisphere.intensity=night?.3:.9;sun.intensity=night?.24:2.4;sun.color.set(night?'#a9c9ff':'#fff0d5');fill.intensity=night?.55:.7;scene.environmentIntensity=night?.18:.38;floor.material.color.set(night?'#334354':'#e5e4da');lamps.forEach(l=>l.intensity=night?28:0);};
$('#home').onclick=()=>home();$('#motion').onclick=()=>{motion=!motion;$('#motion').setAttribute('aria-pressed',String(motion));};$('#zoom-in').onclick=()=>{transition=null;const d=camera.position.clone().sub(controls.target);if(d.length()>3.5)camera.position.copy(controls.target).add(d.multiplyScalar(.82));};$('#zoom-out').onclick=()=>{transition=null;const d=camera.position.clone().sub(controls.target);if(d.length()<48)camera.position.copy(controls.target).add(d.multiplyScalar(1.22));};
controls.addEventListener('start',()=>{transition=null;});
let down=null,multi=false;const pointers=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2();
canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1)multi=true;down=e.button===0?{x:e.clientX,y:e.clientY,moved:false}:null;});canvas.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null;if(!pointers.size)multi=false;});
canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const start=down,skip=multi;down=null;if(!pointers.size)multi=false;if(!start||start.moved||skip||e.button!==0)return;const r=rect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(studio.picks)[0];if(hit)select(hit.object.userData.workerId);});
document.addEventListener('keydown',e=>{if(e.key==='Escape')home();});
home(true);const projected=new T.Vector3();function point(w){projected.copy(w.point).project(camera);const r=rect();return{x:r.left+(projected.x+1)*r.width/2,y:r.top+(1-projected.y)*r.height/2,visible:Math.abs(projected.x)<1&&Math.abs(projected.y)<1};}
let last=0,phase=0,lastTime=0;renderer.setAnimationLoop(time=>{const dt=Math.min(.05,(time-lastTime)/1000);lastTime=time;if(motion)phase+=dt;
 if(transition){const t=Math.min(1,(time-transition.at)/750),ease=1-Math.pow(1-t,3);camera.position.lerpVectors(transition.from,transition.to,ease);controls.target.lerpVectors(transition.start,transition.end,ease);if(t===1)transition=null;}
 for(let i=0;i<studio.workers.length;i++){const w=studio.workers[i];w.head.rotation.y=Math.sin(phase*.48+i)*.14;w.head.rotation.z=Math.sin(phase*.7+i)*.025;if(w.data.status==='running')w.hands.forEach((h,j)=>h.position.y=.94+Math.sin(phase*4+i+j*2)*.018);}
 controls.update();renderer.render(scene,camera);
 if(time-last>60){studio.workers.forEach((w,i)=>{const p=point(w),e=labels[i];e.hidden=!p.visible||!!selected;e.style.left=p.x+'px';e.style.top=(p.y+23)+'px';});last=time;}
});
window.studioDiagnostics=()=>({camera:camera.position.toArray(),night,motion,selected:selected?.data.id,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,points:studio.workers.map(w=>({id:w.data.id,...point(w)}))});document.body.dataset.ready='true';
