import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {buildCampus,buildInterior,roomSpecs} from './universe-art.js';
import {counts,statusNames} from './atlas-data.js';
const $=s=>document.querySelector(s),canvas=$('#scene');
const scene=new T.Scene();scene.background=new T.Color('#e6ebdf');
const renderer=new T.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;
const camera=new T.PerspectiveCamera(40,1,.1,350),controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=180;controls.minPolarAngle=.12;controls.maxPolarAngle=Math.PI*.47;
const pmrem=new T.PMREMGenerator(renderer),environment=new RoomEnvironment();scene.environment=pmrem.fromScene(environment,.04).texture;scene.environmentIntensity=.4;environment.dispose();pmrem.dispose();
const hemi=new T.HemisphereLight('#fff8e6','#79958c',1.1);scene.add(hemi);const sun=new T.DirectionalLight('#fff0cf',2.5);sun.position.set(-35,60,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-45,right:45,top:45,bottom:-45,near:1,far:150});sun.shadow.normalBias=.04;scene.add(sun);
const ground=new T.Mesh(new T.PlaneGeometry(500,500),new T.MeshStandardMaterial({color:'#dde4d5',roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-1;ground.receiveShadow=true;scene.add(ground);
const campus=buildCampus(scene);let interior=null,view='outside',room=null,selected=null,night=false,transition=null;
const r=()=>canvas.getBoundingClientRect(),mobile=()=>innerWidth<=700;
function resize(){const b=r();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas.parentElement);resize();
function move(target,offset,instant=false){const to=target.clone().add(offset);if(instant||matchMedia('(prefers-reduced-motion: reduce)').matches){camera.position.copy(to);controls.target.copy(target);transition=null;controls.update();}else transition={at:performance.now(),from:camera.position.clone(),to,start:controls.target.clone(),end:target};}
function element(tag,content){const e=document.createElement(tag);e.textContent=content;return e;}
function notice(text){$('#notice').textContent=text;}
function clearSelection(){selected=null;$('#detail').hidden=true;interior?.workers.forEach(w=>w.ring.visible=false);}
function sync(){const inside=view==='inside';campus.root.visible=!inside;if(interior)interior.root.visible=inside;$('#inside-nav').hidden=!inside;$('#buildings').hidden=inside;$('#entrance').hidden=view!=='entrance';$('#path').textContent=inside?'/ 숏템메이커 / 1F':view==='entrance'?'/ 숏템메이커 입구':'/ 외부 캠퍼스';$('#eyebrow').textContent=inside?'SHORTEM MAKER / CONNECTED WORKSPACES':'ONE COMPANY · MANY POSSIBILITIES';$('#title').textContent=inside?(room?roomSpecs.find(s=>s.id===room).title:'일이 연결되는 1층.'):view==='entrance'?'숏템메이커 입구':'일하는 세계로 들어오세요.';$('#description').textContent=inside?'방을 선택하면 가까이, 워커를 선택하면 업무까지.':'프로그램 건물을 선택해 내부 공간을 탐색하세요.';$('#scope').textContent=inside?'1F · 예시 워커 16 · 연결된 3구역':'외부 캠퍼스 · 360° 탐색';document.querySelectorAll('[data-room]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.room===room)));}
function outside(instant=false){view='outside';room=null;clearSelection();$('#search').value='';notice('');sync();move(new T.Vector3(0,0,3),new T.Vector3(mobile()?72:52,mobile()?95:65,mobile()?114:79),instant);}
function building(id){if(id!=='shortem'){notice('스탁브레인은 외관 검토 단계입니다. 내부는 아직 연결하지 않았습니다.');return;}view='entrance';room=null;clearSelection();notice('');sync();move(new T.Vector3(-15,1.3,12),new T.Vector3(14,11,24));}
function overview(){clearSelection();room=null;notice('');sync();if(view!=='inside'){outside();return;}roster();move(new T.Vector3(0,0,0),new T.Vector3(mobile()?58:39,mobile()?83:53,mobile()?102:65));}
function focusRoom(id){if(view!=='inside')return;const s=roomSpecs.find(s=>s.id===id);if(!s)return;room=id;clearSelection();$('#search').value='';sync();roster();move(new T.Vector3(s.x,.7,s.z),new T.Vector3(mobile()?20:13,mobile()?28:18,mobile()?36:24));}
function select(id){const w=interior?.workers.find(w=>w.data.id===id);if(view!=='inside'||!w)return;clearSelection();selected=id;room=w.room;sync();roster();interior.workers.forEach(v=>v.ring.visible=v===w);const target=w.point.clone();target.y=1.1;move(target,new T.Vector3(4.5,3.7,6.7));
 const d=$('#detail');d.replaceChildren();d.hidden=false;const close=element('button','×');close.setAttribute('aria-label','상세 닫기');close.onclick=()=>focusRoom(w.room);d.append(close,element('small','WORKER / 예시 배치'),element('h2',id),element('strong',w.data.task));const state=element('span',statusNames[w.data.status]);state.className='state '+w.data.status;d.append(element('br',''),state,element('p',w.data.reason));const dl=document.createElement('dl');for(const [k,v]of [['직급',w.data.role],['보고',w.data.reportTo],['소속',roomSpecs.find(s=>s.id===w.room).title],['실행','실제 시스템 미연결']])dl.append(element('dt',k),element('dd',v));d.append(dl,element('small','지시·중단·터미널은 다음 연결 단계입니다.'));}
function roster(){if(!interior)return;const query=$('#search').value.trim().toLowerCase(),list=$('#workers');list.replaceChildren();const workers=interior.workers.filter(w=>(query||!room||w.room===room)&&(!query||`${w.data.id} ${w.data.task} ${w.data.role}`.toLowerCase().includes(query)));for(const w of workers){const b=element('button',`${w.data.id} · ${w.data.role==='팀장'?'팀장 / ':''}${w.data.task}`);b.dataset.worker=w.data.id;b.onclick=()=>select(w.data.id);list.append(b);}if(!workers.length)list.append(element('small','일치하는 예시 워커가 없습니다.'));}
const labels=[];
function enter(){if(!interior){interior=buildInterior(scene);for(const spec of roomSpecs){const label=document.createElement('div');label.className='room-label';label.style.setProperty('--accent',spec.color);const n=counts(spec.workers);label.append(element('b',spec.title),element('small',`예시 ${n.total} · 실행 ${n.running} · 대기 ${n.waiting} · 막힘 ${n.blocked}`));$('#labels').append(label);labels.push({element:label,point:new T.Vector3(spec.x,3.8,spec.z-6)});}}view='inside';room=null;$('#search').value='';overview();}
for(const spec of roomSpecs){const b=element('button',`${spec.title} · ${spec.workers.length}석`);b.dataset.room=spec.id;b.style.setProperty('--accent',spec.color);b.onclick=()=>focusRoom(spec.id);$('#rooms').append(b);}
document.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>building(b.dataset.building));$('#enter').onclick=enter;$('#outside').onclick=()=>outside();$('#overview').onclick=overview;$('#search').oninput=roster;
$('#night').onclick=()=>{night=!night;document.body.classList.toggle('night',night);$('#night').setAttribute('aria-pressed',String(night));$('#night').textContent=night?'주간으로':'야간으로';scene.background.set(night?'#243848':'#e6ebdf');ground.material.color.set(night?'#29404d':'#dde4d5');hemi.intensity=night?.6:1.1;sun.intensity=night?.5:2.5;sun.color.set(night?'#accfff':'#fff0cf');scene.environmentIntensity=night?.4:.4;};
for(const [id,factor]of [['zoom-in',.8],['zoom-out',1.25]])$('#'+id).onclick=()=>{transition=null;const delta=camera.position.clone().sub(controls.target);delta.setLength(T.MathUtils.clamp(delta.length()*factor,4,180));camera.position.copy(controls.target).add(delta);};controls.addEventListener('start',()=>transition=null);
let down=null,multi=false;const pointers=new Set(),ray=new T.Raycaster();canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1)multi=true;down=e.button===0?{x:e.clientX,y:e.clientY,moved:false}:null;});canvas.addEventListener('pointermove',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null;if(!pointers.size)multi=false;});canvas.addEventListener('pointerup',e=>{const start=down,skip=multi;down=null;pointers.delete(e.pointerId);if(!pointers.size)multi=false;if(!start||start.moved||skip||e.button!==0)return;const b=r();ray.setFromCamera(new T.Vector2((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1),camera);const hit=ray.intersectObjects(view==='inside'?interior.picks:campus.picks)[0];if(hit){if(view==='inside')select(hit.object.userData.workerId);else building(hit.object.userData.building);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(selected)focusRoom(room);else if(view==='inside'&&room)overview();else outside();}});
outside(true);renderer.setAnimationLoop(time=>{if(transition){const t=Math.min(1,(time-transition.at)/800),ease=1-(1-t)**3;camera.position.lerpVectors(transition.from,transition.to,ease);controls.target.lerpVectors(transition.start,transition.end,ease);if(t===1)transition=null;}controls.update();renderer.render(scene,camera);const b=r();for(const label of labels){const p=label.point.clone().project(camera);label.element.hidden=view!=='inside'||!!selected||Math.abs(p.x)>1||Math.abs(p.y)>1||p.z>1;label.element.style.left=(p.x+1)*b.width/2+'px';label.element.style.top=(1-p.y)*b.height/2+'px';}});
function screenPoint(point){const p=point.clone().project(camera),b=r();return {x:b.left+(p.x+1)*b.width/2,y:b.top+(1-p.y)*b.height/2};}
window.universeDiagnostics=()=>({view,room,selected,night,camera:camera.position.toArray(),drawCalls:renderer.info.render.calls,buildings:campus.picks.map(p=>({id:p.userData.building,...screenPoint(p.getWorldPosition(new T.Vector3()))})),workers:interior?.workers.map(w=>({id:w.data.id,room:w.room,position:w.point.toArray(),...screenPoint(w.point)}))||[]});document.body.dataset.ready='true';
